<a href="https://colab.research.google.com/github/devbabbar7/Python-Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [10]:
import numpy as np
#Returns array within a range with stride
arr = np.arange(10,15,2)
print(arr)

# linspace creates n equidistant values between [a,b] (inclusive)
line = np.linspace(0,10,5)
print(line)

[10 12 14]
[ 0.   2.5  5.   7.5 10. ]


In [11]:
arr2 = np.array([21,31,11,0,34,34])
print('Max element',max(arr2))
print('Index of the max value', arr2.argmax())
print('Index of the min value',arr2.argmin())
print('Sort and return indexes',arr2.argsort())

Max element 34
Index of the max value 4
Index of the min value 3
Sort and return indexes [3 2 0 1 4 5]


In [12]:
intvar = np.array([1,2,3,4], np.int8)
intvar2 = np.array([1,2,3,4], dtype = 'int16')
intvar3 = np.array([1,2,3,4], dtype = 'int')
print(intvar)
print(intvar2)
print(intvar3)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [23]:
# shapearr = np.array([[10,11,12,13,14],[2,3]], dtype = 'int') is invalid because the size has to stay the same
shapearr = np.array([[10,11,12,13,14],[2,3,4,5,6],[10,9,8,7,6]], dtype = 'int')
print('Array:\n', shapearr)
print('Type:',type(shapearr))
print('Dimensions:', shapearr.ndim)
print('Shape:', shapearr.shape)
print('Size:', shapearr.size)
print('Size in bytes:', shapearr.nbytes)
print('Sum of x axis:', shapearr.sum(axis=0))
print('Sum of y axis:', shapearr.sum(axis=1))
print('Sum of entire array:', shapearr.sum())
print('Transpose of arr:\n',shapearr.T)
#Ravel converts every array to 1d array like flatten
print('Flatten array using ravel:',shapearr.ravel())
print('Filter values:', np.where(shapearr.ravel()>5))
print('Number of non-zero elements:', np.count_nonzero(shapearr))
print('Reshape:\n',shapearr.reshape(5,-1))
print('Max element:', shapearr.max())
print('Min element:', shapearr.min())

Array:
 [[10 11 12 13 14]
 [ 2  3  4  5  6]
 [10  9  8  7  6]]
Type: <class 'numpy.ndarray'>
Dimensions: 2
Shape: (3, 5)
Size: 15
Size in bytes: 120
Sum of x axis: [22 23 24 25 26]
Sum of y axis: [60 20 40]
Sum of entire array: 120
Transpose of arr:
 [[10  2 10]
 [11  3  9]
 [12  4  8]
 [13  5  7]
 [14  6  6]]
Flatten array using ravel: [10 11 12 13 14  2  3  4  5  6 10  9  8  7  6]
Filter values: (array([ 0,  1,  2,  3,  4,  9, 10, 11, 12, 13, 14]),)
Number of non-zero elements: 15
Reshape:
 [[10 11 12]
 [13 14  2]
 [ 3  4  5]
 [ 6 10  9]
 [ 8  7  6]]
Max element: 14
Min element: 2


In [14]:
# flat is like an iterator
flatx = shapearr.flat
print(flatx)
for item in flatx:
  print(item)

10
11
12
13
14
2
3
4
5
6
10
9
8
7
6


In [15]:
# A 4x6 matrix with random values
emp = np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [16]:
#Return a new array with the same shape and type as a given array
emp_like = np.empty_like(emp)
emp_like

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [17]:
ide2 = np.identity(4)
ide2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr1 = np.array([1,2,3,4,5],dtype = 'int')
arr2 = np.array([6,7,8,9,10], dtype = 'int')
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr1/arr2)
print(np.sqrt(arr2))
print(np.log(arr2))
print(np.log10(arr2))

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
[0.77815125 0.84509804 0.90308999 0.95424251 1.        ]
